### ISSUE TITLE
Icons not displayed on One Plus 5 (8.1.0)

### ISSUE THREAD

**Issue by lutrampal** [lutrampal/sbeereck-app#27]

**Comment by DylanFayant** [comment]
To resolve this "dev*" bug you have to : 
1) go to the project "front-end" directory through the terminal 
2) type de following command : `react-native link` to link the dependencies
3) re-run the project with `react-native run-android` to apply the changes
Et voilà 

* Dev bug because this issue is nonexistent in the production mode (thanks to the compilation)
